# document_AIKIF.py written by Duncan Murray 18/4/2014
# All Python Program Statistics
# 26/08/2014 : Files =  110  Bytes =  377221  Lines =  10694  Lines of Code =  8836
# 30/10/2014 : Files =  127  Bytes =  444760  Lines =  12595  Lines of Code =  10409

import sys
import os
sys.path.append('..')

import programs as mod_prg
import aikif.lib.cls_filelist as mod_fl
import aikif.lib.cls_file as mod_file

def main():
    """
    Example of self documenting (of sorts) code, via aikif.
    Simply call functions like below to build an overview 
    which has metadata automatically updated.
    """
    # Dont use - this is useless #get_list_of_applications()
    document_programs()
    #list_all_python_programs()
    
    
    
def document_programs():
    """
    Document a subset of all programs with purpose (and intent)
    """
    p = mod_prg.Programs('AIKIF Programs', 'T:\\user\\dev\\src\\python\\AIKIF')
    p.comment('program.py', 'test program')
    p.comment('cls_file_mapping.py', 'uses ontology to get list of files to save data')
    p.comment('index.py', 'rebuilds indexes')
    
    """
    p.add('view.py', 'view the data in AIKIF')
    p.add('AIKIF_utils.py', 'utils for getting standard file structures (soon to be deprecated)')
    p.add('AI.py', 'original main entry point - soon to be deprecated')
    p.add('add.py', 'command line utility to add information - not yet implemented')
    p.add('dataTools.py', 'data tools to manage database access')
    p.add('AIKIF_create.py', 'creates default structures with test data')
    p.add('generateTestData.py', 'Tool to generate various test data')
    p.add('processRawData.py', 'calls various sub tasks to collect raw data')
    p.add('loadInfoCourseLectures.py', 'loads course lecture notes into AIKIF')
    p.add('loadPIM_Filelist.py', 'loads generic filelists into AIKIF - indexing not implemented')
    p.add('loadCountry_Gdeltproject.py', 'sample load - loads country data into AIKIF')
    p.add('loadPIM_shoppingList.py', 'sample data - loads a users shopping list into AIKIF')
    p.add('security.py', 'future module to handle security and privacy settings')

"""
    p.list()	# get list of all programs
    p.save()
    p.collect_program_info('progress.md')


def get_list_of_applications():
    """
    Get list of applications
    """
    apps = mod_prg.Programs('Applications', 'C:\\apps')
    fl = mod_fl.FileList(['C:\\apps'], ['*.exe'], ["\\bk\\"])
    for file in fl.get_list():
        apps.add(file, 'autogenerated list')
    apps.list()
    apps.save()


if __name__ == '__main__': 
    main()